/**
 * Created by idoschachter on 23/08/2016.
 */
module.exports = {
    DISPLAY_ERROR : 'DISPLAY_ERROR',

    ROOMS_SELECT_CURRENT_ROOM: 'ROOMS_SELECT_CURRENT_ROOM',
    ROOMS_RECEIVE_DATA : 'ROOMS_RECEIVE_DATA',
    ROOMS_RECEIVE_DATA_ERROR: 'ROOMS_RECEIVE_DATA_ERROR',
    ROOMS_SET_ROOM_IMAGE: 'ROOMS_SET_ROOM_IMAGE',

    FACTS_RECEIVE_DATA : 'FACTS_RECEIVE_DATA',
    FACTS_RECEIVE_DATA_ERROR: 'FACTS_RECEIVE_DATA_ERROR',
    FACTS_SET_FACT_INDEX: 'FACTS_SET_FACT_INDEX',

    CONTROL_TIME: 'CONTROL_TIME'
};