/**
 * Created by idoschachter on 23/08/2016.
 */
module.exports = {
    DISPLAY_ERROR : 'DISPLAY_ERROR',
    ROOMS_RECEIVE_DATA : 'ROOMS_RECEIVE_DATA',
    ROOMS_RECEIVE_DATA_ERROR: 'ROOMS_RECEIVE_DATA_ERROR',
    FACTS_RECEIVE_DATA : 'FACTS_RECEIVE_DATA',
    FACTS_RECEIVE_DATA_ERROR: 'FACTS_RECEIVE_DATA_ERROR',
};